Don't merge, issue found ``` 2024-04-17 11:46:55.955 Uncaught app exception Traceback (most recent call last):   File "C:\Users\HP\miniconda3\envs\partneresi\lib\site-packages\langchain_community\document_loaders\csv_loader.py", line 70, in load     docs = self.__read_file(csvfile)   File "C:\Users\HP\miniconda3\envs\partneresi\lib\site-packages\langchain_community\document_loaders\csv_loader.py", line 94, in __read_file     for i, row in enumerate(csv_reader):   File "C:\Users\HP\miniconda3\envs\partneresi\lib\csv.py", line 111, in __next__     row = next(self.reader)   File "C:\Users\HP\miniconda3\envs\partneresi\lib\encodings\cp1252.py", line 23, in decode     return codecs.charmap_decode(input,self.errors,decoding_table)[0] UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 342: character maps to <undefined>
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\miniconda3\envs\partneresi\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\HP\Documents\partner-esi-llm-chatbot\app.py", line 72, in <module>
    main()
  File "C:\Users\HP\Documents\partner-esi-llm-chatbot\app.py", line 31, in main
    chatbot = ChatBot(portfolio_id = '539', directory_paths = FILE, memory = st.session_state.buffer_memory)
  File "C:\Users\HP\Documents\partner-esi-llm-chatbot\chat.py", line 22, in __init__
    self.userdb = createVector(self.user_file_path)
  File "C:\Users\HP\Documents\partner-esi-llm-chatbot\vectordb.py", line 19, in createVector
    sections = loader.load()
  File "C:\Users\HP\miniconda3\envs\partneresi\lib\site-packages\langchain_community\document_loaders\csv_loader.py", line 84, in load
    raise RuntimeError(f"Error loading {self.file_path}") from e
RuntimeError: Error loading dat\output\pid_539_processed_data.csv
```